apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khimnguynnn/Helm-X-Kustomize-X-ArgoCD.git
    targetRevision: main
    path: overlays/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: app-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true