apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/app-dev.yaml
  - namespaces/app-stg.yaml
  - namespaces/app-prd.yaml

helmGlobals:
  chartHome: ../charts
  configHome: .helm
